name: Update index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Fetch plugin manifests and generate a list of plugins
        run: go run cmd/crawler/main.go site/data/index.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update index.yaml
          title: Update index.yaml
          body: |
            This PR updates the index.yaml file.
          reviewers: |
            knqyf263
            DmitriyLewenkk
          add-paths: |
            site/data/index.yaml